"""
STEP 4 - YAMNet transfer learning.

The backbone stays frozen. Only a small head is trained:

    1024-d embedding -> Dense(128, relu) -> Dropout(0.4) -> Dense(2, softmax)

That is ~131 k trainable parameters against 3.2 M frozen ones, which is the
whole point of transfer learning here: 665 training clips could never fit an
audio CNN from scratch, but they are ample for re-mapping a feature space
AudioSet already learned from ~2 M clips.

Because the backbone is frozen, it is run exactly **once**. Every window's
embedding is computed up front and cached, and training then iterates over
1024-float vectors instead of re-running a 3.2 M parameter CNN each epoch. This
turns epochs from minutes into fractions of a second.

Two correctness guards run before any training happens:

  * the rebuilt front-end + backbone is verified numerically against TF-Hub, so
    the head cannot be trained on a feature space the device will not reproduce;
  * embeddings are extracted through the *rebuilt* model, not TF-Hub, so the
    features used for training are byte-for-byte the ones Step 5 exports.

Outputs
    models/yamnet_fall_detector.keras   float32 composite (patch -> 2 classes)
    models/yamnet_fall_detector.h5      same, legacy format
    models/fall_head.keras              head alone
    data/processed/embeddings.npy       cached 1024-d embeddings
    outputs/train_metrics.json, outputs/training_history.csv
    outputs/figures/train_curves.png

Usage
    python src/4_train.py
    python src/4_train.py --epochs 300 --batch-size 128
    python src/4_train.py --skip-verify        # only if already verified
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config

LOGGER = logging.getLogger("train")


def setup_logging(log_path: Path) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    LOGGER.setLevel(logging.INFO)
    LOGGER.handlers.clear()
    # tensorflow_hub installs a root-logger handler; without this
    # every line would be emitted twice.
    LOGGER.propagate = False
    console = logging.StreamHandler(sys.stdout)
    console.setFormatter(logging.Formatter("%(message)s"))
    LOGGER.addHandler(console)
    handler = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)-7s %(message)s"))
    LOGGER.addHandler(handler)


def section(title: str) -> None:
    LOGGER.info("\n" + "=" * 78)
    LOGGER.info(title)
    LOGGER.info("=" * 78)


def indent(text: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line for line in text.splitlines())


# ---------------------------------------------------------------------------
# Embedding extraction
# ---------------------------------------------------------------------------


def _chunks_hash(chunks: np.ndarray) -> str:
    """Return a fast SHA-256 fingerprint of the chunks array content.

    Hashes a 1 MB sample (first+middle+last blocks) rather than the full
    444 MB array — fast enough to run every time, sensitive enough to catch
    any Step-2 regeneration that changes the audio content.
    """
    import hashlib
    h = hashlib.sha256()
    n = chunks.shape[0]
    # Sample ~1 MB worth of rows from start, middle, and end
    sample_rows = max(1, 1024 * 1024 // (chunks.shape[1] * 2))  # 2 bytes per int16
    for start in (0, max(0, n // 2 - sample_rows // 2), max(0, n - sample_rows)):
        end = min(start + sample_rows, n)
        h.update(np.asarray(chunks[start:end]).tobytes())
    h.update(str(chunks.shape).encode())
    return h.hexdigest()


def extract_embeddings(
    chunks: np.ndarray, backbone, batch_size: int, cache_path: Path, force: bool
) -> np.ndarray:
    """Run every window through the frozen backbone once, and cache the result.

    A SHA-256 sidecar file (`<cache_path>.sha256`) records the fingerprint of
    the chunks array used to build the cache. If chunks were regenerated by
    Step 2 (different RIRs, negatives, etc.), the fingerprint changes and the
    cache is automatically invalidated — preventing the silent stale-cache bug
    where the head trains on embeddings from a different audio set than Step 5
    evaluates on.
    """
    import tensorflow as tf
    import yamnet_model as ym

    hash_path = cache_path.with_suffix(".sha256")

    if cache_path.exists() and not force:
        cached = np.load(cache_path, mmap_mode="r")
        if cached.shape == (chunks.shape[0], config.EMBEDDING_DIM):
            # Verify the cache was built from the current chunks content
            current_hash = _chunks_hash(chunks)
            stored_hash = hash_path.read_text().strip() if hash_path.exists() else ""
            if current_hash == stored_hash:
                LOGGER.info("Reusing cached embeddings: %s %s", cache_path, cached.shape)
                return np.asarray(cached)
            LOGGER.info(
                "Chunks content has changed since cache was built "
                "(Step 2 was re-run with different settings). Recomputing embeddings."
            )
        else:
            LOGGER.info("Cache shape %s does not match corpus; recomputing.", cached.shape)

    inputs = tf.keras.Input(shape=(config.WINDOW_SAMPLES,), dtype=tf.float32)
    extractor = tf.keras.Model(
        inputs, backbone(ym.LogMelLayer(name="log_mel")(inputs)), name="extractor"
    )

    total = chunks.shape[0]
    out = np.zeros((total, config.EMBEDDING_DIM), dtype=np.float32)
    from tqdm import tqdm

    for start in tqdm(
        range(0, total, batch_size), desc="Embedding", unit="batch", ncols=78,
        disable=not sys.stderr.isatty(),
    ):
        stop = min(start + batch_size, total)
        batch = np.asarray(chunks[start:stop], dtype=np.float32) / 32768.0
        out[start:stop] = extractor(batch, training=False).numpy()

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(cache_path, out)
    # Write hash sidecar so future runs can detect if chunks were regenerated
    hash_path.write_text(_chunks_hash(chunks))
    LOGGER.info("Cached embeddings -> %s (%.1f MB)",
                cache_path, cache_path.stat().st_size / 1e6)
    return out


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------


def evaluate(model, x, y, name: str) -> dict:
    """Accuracy plus per-class precision/recall/F1 for one split."""
    from sklearn.metrics import (
        accuracy_score, confusion_matrix, precision_recall_fscore_support,
        roc_auc_score,
    )

    probs = model.predict(x, verbose=0)
    pred = probs.argmax(axis=1)
    fall = config.LABEL_TO_INDEX["fall"]

    precision, recall, f1, support = precision_recall_fscore_support(
        y, pred, labels=[0, 1], zero_division=0
    )
    try:
        auc = float(roc_auc_score(y, probs[:, fall]))
    except ValueError:
        auc = float("nan")

    result = {
        "split": name,
        "n": int(len(y)),
        "accuracy": float(accuracy_score(y, pred)),
        "auc": auc,
        "confusion_matrix": confusion_matrix(y, pred, labels=[0, 1]).tolist(),
        "fall_precision": float(precision[fall]),
        "fall_recall": float(recall[fall]),
        "fall_f1": float(f1[fall]),
        "per_class": {
            config.INDEX_TO_LABEL[i]: {
                "precision": float(precision[i]), "recall": float(recall[i]),
                "f1": float(f1[i]), "support": int(support[i]),
            }
            for i in (0, 1)
        },
    }
    return result


def evaluate_clips(model, x, y, clip_uids, name: str) -> dict:
    """Clip-level metrics, averaging each clip's window probabilities.

    Window-level labelling is inherently noisy here. A 3 s SAFE clip is sliced
    into five windows and all five inherit the clip's label, but the impact
    itself lasts a fraction of a second and sits mid-clip. Measured mean P(fall)
    by window position confirms it: ~0.49 / 0.85 / 0.92 / 0.92 / 0.60 across
    positions 0-4. The first and last windows are largely background wearing a
    'fall' label, and no model can fit that.

    Averaging over a clip's windows recovers the real signal, and it matches how
    the device should behave: an alerting system can integrate over a second or
    two before raising an alarm rather than firing on a single window.

    Mean is used rather than max deliberately -- max triggers on any single
    confident window and measured far worse (0.68 vs 0.92 accuracy), because it
    turns one spurious window into a false alarm for the whole clip.
    """
    from sklearn.metrics import (
        accuracy_score, confusion_matrix, precision_recall_fscore_support,
        roc_auc_score,
    )

    fall = config.LABEL_TO_INDEX["fall"]
    probs = model.predict(x, verbose=0)[:, fall]
    frame = pd.DataFrame({"uid": clip_uids, "y": y, "p": probs})
    grouped = frame.groupby("uid").agg(y=("y", "first"), p=("p", "mean"))
    pred = (grouped["p"] > 0.5).astype(int).to_numpy()
    truth = grouped["y"].to_numpy()

    precision, recall, f1, _ = precision_recall_fscore_support(
        truth, pred, labels=[0, 1], zero_division=0
    )
    try:
        auc = float(roc_auc_score(truth, grouped["p"].to_numpy()))
    except ValueError:
        auc = float("nan")
    return {
        "split": f"{name}/clip",
        "n": int(len(truth)),
        "accuracy": float(accuracy_score(truth, pred)),
        "auc": auc,
        "confusion_matrix": confusion_matrix(truth, pred, labels=[0, 1]).tolist(),
        "fall_precision": float(precision[fall]),
        "fall_recall": float(recall[fall]),
        "fall_f1": float(f1[fall]),
    }


def log_metrics(result: dict) -> None:
    LOGGER.info(
        "%-6s n=%-6d acc=%.4f  auc=%.4f  fall P=%.4f R=%.4f F1=%.4f",
        result["split"], result["n"], result["accuracy"], result["auc"],
        result["fall_precision"], result["fall_recall"], result["fall_f1"],
    )


def write_curves(history: pd.DataFrame) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for ax, (key, title) in zip(
        axes, (("loss", "Loss"), ("accuracy", "Accuracy"),
               ("learning_rate", "Learning rate"))
    ):
        if key in history:
            ax.plot(history.index, history[key], label="train", color="#3b7dd8")
        val_key = f"val_{key}"
        if val_key in history:
            ax.plot(history.index, history[val_key], label="val", color="#d1495b")
        ax.set_xlabel("epoch")
        ax.set_title(title)
        if key == "learning_rate":
            ax.set_yscale("log")
        if ax.get_legend_handles_labels()[0]:
            ax.legend()
    fig.tight_layout()
    path = config.FIGURES_DIR / "train_curves.png"
    config.FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=140)
    plt.close(fig)
    return path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train the YAMNet fall-detection head.")
    p.add_argument("--processed-dir", type=Path, default=config.PROCESSED_DIR)
    p.add_argument("--splits-dir", type=Path, default=config.SPLITS_DIR)
    p.add_argument("--models-dir", type=Path, default=config.MODELS_DIR)
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--batch-size", type=int, default=64)
    p.add_argument("--extract-batch", type=int, default=128)
    p.add_argument("--learning-rate", type=float, default=1e-3)
    p.add_argument("--hidden-units", type=int, default=128)
    p.add_argument("--dropout", type=float, default=0.4)
    p.add_argument("--patience", type=int, default=15)
    p.add_argument("--lr-patience", type=int, default=6)
    p.add_argument("--seed", type=int, default=config.RANDOM_SEED)
    p.add_argument("--force-extract", action="store_true")
    p.add_argument("--skip-verify", action="store_true")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    config.ensure_dirs()
    setup_logging(config.LOGS_DIR / "train.log")

    import tensorflow as tf
    import yamnet_model as ym

    tf.keras.utils.set_random_seed(args.seed)

    section("YAMNET TRANSFER LEARNING  -  Step 4")
    LOGGER.info("TensorFlow ......... %s", tf.__version__)

    chunks_path = args.processed_dir / "chunks_int16.npy"
    if not chunks_path.exists():
        LOGGER.info("Missing %s - run Step 2 first.", chunks_path)
        return 2
    indices = {}
    for name in ("train", "val", "test"):
        path = args.splits_dir / f"{name}_indices.npy"
        if not path.exists():
            LOGGER.info("Missing %s - run Step 3 first.", path)
            return 2
        indices[name] = np.load(path)

    chunks = np.load(chunks_path, mmap_mode="r")
    manifest = pd.read_csv(
        args.splits_dir / "split_manifest.csv",
        dtype={"clip_uid": str, "fold_id": str},
    )
    labels = manifest.set_index("chunk_index")["label_index"].to_numpy()
    LOGGER.info("Windows ............ %d", chunks.shape[0])
    LOGGER.info("train/val/test ..... %d / %d / %d",
                *(len(indices[s]) for s in ("train", "val", "test")))

    # --- backbone ---
    section("FROZEN BACKBONE")
    weights = ym.download_weights(args.models_dir)
    backbone = ym.build_backbone(include_logits=False)
    applied = ym.load_yamnet_weights(backbone, weights)
    backbone.trainable = False
    LOGGER.info("weights ............ %s (%.1f MB)", weights.name,
                weights.stat().st_size / 1e6)
    LOGGER.info("layers populated ... %d", applied)
    LOGGER.info("parameters ......... %d frozen", backbone.count_params())

    checks: dict | None = None
    if not args.skip_verify:
        section("REBUILD VERIFICATION vs TF-HUB")
        LOGGER.info(
            "The head must be trained on the same feature space the device\n"
            "will compute. Comparing the rebuilt front-end and backbone against\n"
            "TF-Hub YAMNet on real corpus audio.\n"
        )
        sample = np.stack([
            np.asarray(chunks[i], dtype=np.float32) / 32768.0
            for i in np.linspace(0, chunks.shape[0] - 1, 6, dtype=int)
        ])
        checks = ym.verify_against_hub(sample, backbone)
        for key, value in checks.items():
            LOGGER.info("  %-26s %.4e", key, value)
        if checks["relative_embedding_diff"] > 1e-3:
            LOGGER.info(
                "\nFAIL: rebuilt backbone diverges from TF-Hub. Refusing to train."
            )
            return 1
        LOGGER.info("\nPASS - rebuild matches TF-Hub to floating-point noise.")

    # --- embeddings ---
    section("EMBEDDING EXTRACTION")
    embeddings = extract_embeddings(
        chunks, backbone, args.extract_batch,
        args.processed_dir / "embeddings.npy", args.force_extract,
    )
    LOGGER.info("embeddings ......... %s", embeddings.shape)

    x = {s: embeddings[indices[s]] for s in indices}
    y = {s: labels[indices[s]] for s in indices}
    for name in ("train", "val", "test"):
        counts = np.bincount(y[name], minlength=config.NUM_CLASSES)
        LOGGER.info("  %-5s %5d windows  non_fall=%d fall=%d",
                    name, len(y[name]), counts[0], counts[1])

    # --- head ---
    section("CLASSIFICATION HEAD")
    head = ym.build_head(hidden_units=args.hidden_units, dropout=args.dropout)
    head.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=args.learning_rate),
        loss="sparse_categorical_crossentropy",
        # AUC is deliberately absent: Keras' AUC metric expects a single
        # binary output, not a 2-class softmax with sparse labels. It is
        # computed from probabilities by sklearn in evaluate() instead.
        metrics=["accuracy"],
    )
    head.summary(print_fn=LOGGER.info)

    summary_path = args.splits_dir / "splits_summary.json"
    weights_map = None
    if summary_path.exists():
        raw = json.loads(summary_path.read_text()).get("class_weights", {})
        weights_map = {int(k): float(v) for k, v in raw.items()}
        LOGGER.info("class weights ...... %s", weights_map)

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=args.patience,
            restore_best_weights=True, verbose=1,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=args.lr_patience,
            min_lr=1e-6, verbose=1,
        ),
    ]

    section("TRAINING")
    history = head.fit(
        x["train"], y["train"],
        validation_data=(x["val"], y["val"]),
        epochs=args.epochs, batch_size=args.batch_size,
        class_weight=weights_map, callbacks=callbacks, verbose=2,
    )
    frame = pd.DataFrame(history.history)
    frame.index.name = "epoch"
    frame.to_csv(config.OUTPUTS_DIR / "training_history.csv")
    LOGGER.info("\nEpochs run ......... %d", len(frame))
    LOGGER.info("Best val_loss ...... %.4f (epoch %d)",
                frame["val_loss"].min(), int(frame["val_loss"].idxmin()))

    # --- metrics ---
    section("METRICS")
    results = [evaluate(head, x[s], y[s], s) for s in ("train", "val", "test")]
    for result in results:
        log_metrics(result)

    LOGGER.info("\nClip-level (mean over each clip's windows):")
    uids = manifest.set_index("chunk_index")["clip_uid"]
    for name in ("val", "test"):
        clip_result = evaluate_clips(
            head, x[name], y[name], uids.loc[indices[name]].to_numpy(), name
        )
        log_metrics(clip_result)
        results.append(clip_result)
    LOGGER.info(
        "\nTest numbers are reported here for visibility only; Step 5 does the\n"
        "full confusion-matrix and threshold analysis on the quantised model."
    )

    # --- save ---
    section("SAVING MODELS")
    args.models_dir.mkdir(parents=True, exist_ok=True)
    composite = ym.build_composite(backbone, head)
    composite.compile()

    head_path = args.models_dir / "fall_head.keras"
    head.save(head_path)
    keras_path = args.models_dir / "yamnet_fall_detector.keras"
    composite.save(keras_path)
    LOGGER.info("head ............... %s", head_path)
    LOGGER.info("composite (.keras) . %s (%.1f MB)", keras_path,
                keras_path.stat().st_size / 1e6)

    h5_path = args.models_dir / "yamnet_fall_detector.h5"
    try:
        composite.save(h5_path)
        LOGGER.info("composite (.h5) .... %s (%.1f MB)", h5_path,
                    h5_path.stat().st_size / 1e6)
    except Exception as exc:  # noqa: BLE001 - legacy format is best-effort
        LOGGER.info("composite (.h5) .... not written (%s: %s)",
                    type(exc).__name__, exc)

    LOGGER.info("\nComposite input  ... %s", composite.input_shape)
    LOGGER.info("Composite output ... %s", composite.output_shape)
    LOGGER.info("Total parameters ... %d (%d trainable)",
                composite.count_params(),
                sum(int(np.prod(w.shape)) for w in composite.trainable_weights))

    metrics = {
        "tensorflow": tf.__version__,
        "epochs_run": int(len(frame)),
        "best_val_loss": float(frame["val_loss"].min()),
        "best_epoch": int(frame["val_loss"].idxmin()),
        "hidden_units": args.hidden_units,
        "dropout": args.dropout,
        "learning_rate": args.learning_rate,
        "batch_size": args.batch_size,
        "seed": args.seed,
        "verification": checks,
        "results": {r["split"]: r for r in results},
    }
    (config.OUTPUTS_DIR / "train_metrics.json").write_text(
        json.dumps(metrics, indent=2), encoding="utf-8"
    )

    curves = write_curves(frame)
    section("ARTEFACTS")
    LOGGER.info("metrics .... %s", config.OUTPUTS_DIR / "train_metrics.json")
    LOGGER.info("history .... %s", config.OUTPUTS_DIR / "training_history.csv")
    LOGGER.info("figure ..... %s", curves)

    section("RESULT")
    val = next(r for r in results if r["split"] == "val")
    LOGGER.info("Validation accuracy %.4f, fall F1 %.4f. Ready for Step 5.",
                val["accuracy"], val["fall_f1"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
