"""
STEP 5 - TFLite export, INT8 post-training quantization, and C header generation.

This step bridges the desktop ML pipeline to the ESP32-S3 firmware:

1. Wraps the trained composite model (96, 64, 1) log-mel patch -> 2 classes with a
   static batch size of 1, required by TensorFlow Lite Micro on microcontrollers.
2. Converts the baseline Float32 model to TFLite format.
3. Performs full INT8 Post-Training Quantization (PTQ) using representative
   calibration log-mel patches generated from the training split.
4. Validates numerical parity between Float32 and INT8 on the held-out test and
   validation splits, reporting window-level and clip-level metrics (accuracy,
   recall, precision, F1, AUC, and confusion matrices).
5. Sweeps decision thresholds to evaluate the precision/recall trade-off.
6. Exports the quantized model as a 16-byte aligned C byte array header and
   source file (`yamnet_model_data.h` and `yamnet_model_data.cc`) with exact
   quantization scale and zero-point parameters for direct compilation into
   the ESP32-S3 firmware.

Outputs
    models/yamnet_fall_detector_float32.tflite
    models/yamnet_fall_detector_int8.tflite
    models/yamnet_model_data.h
    models/yamnet_model_data.cc
    outputs/tflite_metrics.json
    outputs/figures/tflite_eval.png
    outputs/logs/export_tflite.log

Usage
    python src/5_export_tflite.py
    python src/5_export_tflite.py --num-calibration 400
    python src/5_export_tflite.py --skip-eval
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_recall_fscore_support,
    roc_auc_score,
    roc_curve,
)

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config
import yamnet_model as ym

LOGGER = logging.getLogger("export_tflite")


def setup_logging(log_path: Path) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    LOGGER.setLevel(logging.INFO)
    LOGGER.handlers.clear()
    LOGGER.propagate = False
    console = logging.StreamHandler(sys.stdout)
    console.setFormatter(logging.Formatter("%(message)s"))
    LOGGER.addHandler(console)
    handler = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)-7s %(message)s"))
    LOGGER.addHandler(handler)


def section(title: str) -> None:
    LOGGER.info("\n" + "=" * 78)
    LOGGER.info(title)
    LOGGER.info("=" * 78)


def indent(text: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line for line in text.splitlines())


# ---------------------------------------------------------------------------
# C Header & Source Exporter
# ---------------------------------------------------------------------------


def export_c_array(
    tflite_bytes: bytes,
    header_path: Path,
    source_path: Path,
    input_scale: float,
    input_zero_point: int,
    output_scale: float,
    output_zero_point: int,
) -> None:
    """Generate C header and source files containing the aligned TFLite model data."""
    header_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.parent.mkdir(parents=True, exist_ok=True)

    header_content = f"""// Auto-generated by src/5_export_tflite.py
// Acoustic Emergency Alerting System - ESP32-S3-BOX-3 Model Data
#ifndef YAMNET_MODEL_DATA_H_
#define YAMNET_MODEL_DATA_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

// Model input/output dimensions
#define YAMNET_INPUT_FRAMES       {config.PATCH_FRAMES}
#define YAMNET_INPUT_BANDS        {config.MEL_BANDS}
#define YAMNET_INPUT_CHANNELS     1
#define YAMNET_NUM_CLASSES        {config.NUM_CLASSES}

// Input quantization parameters (int8):
//   quantized_val = round(real_val / YAMNET_INPUT_SCALE) + YAMNET_INPUT_ZERO_POINT
//   real_val      = (quantized_val - YAMNET_INPUT_ZERO_POINT) * YAMNET_INPUT_SCALE
#define YAMNET_INPUT_SCALE        {input_scale:.8e}f
#define YAMNET_INPUT_ZERO_POINT   {input_zero_point}

// Output quantization parameters (int8):
//   probability   = (quantized_val - YAMNET_OUTPUT_ZERO_POINT) * YAMNET_OUTPUT_SCALE
#define YAMNET_OUTPUT_SCALE       {output_scale:.8e}f
#define YAMNET_OUTPUT_ZERO_POINT  {output_zero_point}

// Model FlatBuffer binary (16-byte aligned for TFLite Micro in PSRAM/Flash)
extern const unsigned char g_yamnet_model_data[];
extern const unsigned int g_yamnet_model_data_len;

#ifdef __cplusplus
}}
#endif

#endif  // YAMNET_MODEL_DATA_H_
"""

    with open(header_path, "w", encoding="utf-8") as f:
        f.write(header_content)

    # Format bytes in hex columns
    hex_lines = []
    line_bytes = []
    for i, b in enumerate(tflite_bytes):
        line_bytes.append(f"0x{b:02x}")
        if len(line_bytes) == 12 or i == len(tflite_bytes) - 1:
            hex_lines.append("    " + ", ".join(line_bytes) + ",")
            line_bytes = []

    body = "\n".join(hex_lines)
    source_content = f"""// Auto-generated by src/5_export_tflite.py
#include "{header_path.name}"

#if defined(__GNUC__) || defined(__clang__)
#define YAMNET_ALIGN __attribute__((aligned(16)))
#else
#define YAMNET_ALIGN alignas(16)
#endif

YAMNET_ALIGN const unsigned char g_yamnet_model_data[] = {{
{body}
}};

const unsigned int g_yamnet_model_data_len = {len(tflite_bytes)};
"""

    with open(source_path, "w", encoding="utf-8") as f:
        f.write(source_content)


# ---------------------------------------------------------------------------
# TFLite Inference Helper
# ---------------------------------------------------------------------------


class TFLiteWrapper:
    """Convenience wrapper around tf.lite.Interpreter for batch inference."""

    def __init__(self, model_bytes: bytes):
        import tensorflow as tf

        self.interpreter = tf.lite.Interpreter(model_content=model_bytes)
        self.interpreter.allocate_tensors()
        self.input_details = self.interpreter.get_input_details()[0]
        self.output_details = self.interpreter.get_output_details()[0]
        self.is_int8 = self.input_details["dtype"] == np.int8

        self.input_scale, self.input_zero_point = self.input_details["quantization"]
        self.output_scale, self.output_zero_point = self.output_details["quantization"]

    def predict_one(self, patch_f32: np.ndarray) -> np.ndarray:
        """Run single (1, 96, 64, 1) patch. Returns (2,) probabilities."""
        if self.is_int8:
            q_input = np.clip(
                np.round(patch_f32 / self.input_scale + self.input_zero_point),
                -128,
                127,
            ).astype(np.int8)
            self.interpreter.set_tensor(self.input_details["index"], q_input)
            self.interpreter.invoke()
            q_output = self.interpreter.get_tensor(self.output_details["index"])[0]
            probs = (q_output.astype(np.float32) - self.output_zero_point) * self.output_scale
            # Renormalize to ensure clean sum=1
            s = probs.sum()
            if s > 0:
                probs = probs / s
            return probs
        else:
            self.interpreter.set_tensor(
                self.input_details["index"], patch_f32.astype(np.float32)
            )
            self.interpreter.invoke()
            return self.interpreter.get_tensor(self.output_details["index"])[0]

    def predict_batch(self, patches: np.ndarray) -> np.ndarray:
        """Run array of (N, 96, 64, 1) patches. Returns (N, 2) probabilities."""
        n = patches.shape[0]
        probs = np.zeros((n, config.NUM_CLASSES), dtype=np.float32)
        for i in range(n):
            probs[i] = self.predict_one(patches[i : i + 1])
        return probs


# ---------------------------------------------------------------------------
# Metrics & Analysis
# ---------------------------------------------------------------------------


def compute_metrics(y_true: np.ndarray, probs: np.ndarray, threshold: float = 0.5) -> dict:
    fall_idx = config.LABEL_TO_INDEX["fall"]
    fall_probs = probs[:, fall_idx]
    y_pred = (fall_probs >= threshold).astype(int)

    precision, recall, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=[0, 1], zero_division=0
    )
    try:
        auc = float(roc_auc_score(y_true, fall_probs))
    except ValueError:
        auc = float("nan")

    return {
        "n": int(len(y_true)),
        "threshold": float(threshold),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "auc": auc,
        "confusion_matrix": confusion_matrix(y_true, y_pred, labels=[0, 1]).tolist(),
        "fall_precision": float(precision[fall_idx]),
        "fall_recall": float(recall[fall_idx]),
        "fall_f1": float(f1[fall_idx]),
        "non_fall_precision": float(precision[0]),
        "non_fall_recall": float(recall[0]),
        "non_fall_f1": float(f1[0]),
    }


def compute_clip_metrics(
    uids: np.ndarray, y_true: np.ndarray, probs: np.ndarray, threshold: float = 0.5
) -> dict:
    fall_idx = config.LABEL_TO_INDEX["fall"]
    fall_probs = probs[:, fall_idx]
    df = pd.DataFrame({"uid": uids, "y": y_true, "p": fall_probs})
    grouped = df.groupby("uid").agg(y=("y", "first"), p=("p", "mean"))

    truth = grouped["y"].to_numpy()
    mean_probs = grouped["p"].to_numpy()
    pred = (mean_probs >= threshold).astype(int)

    precision, recall, f1, _ = precision_recall_fscore_support(
        truth, pred, labels=[0, 1], zero_division=0
    )
    try:
        auc = float(roc_auc_score(truth, mean_probs))
    except ValueError:
        auc = float("nan")

    return {
        "n_clips": int(len(truth)),
        "threshold": float(threshold),
        "accuracy": float(accuracy_score(truth, pred)),
        "auc": auc,
        "confusion_matrix": confusion_matrix(truth, pred, labels=[0, 1]).tolist(),
        "fall_precision": float(precision[fall_idx]),
        "fall_recall": float(recall[fall_idx]),
        "fall_f1": float(f1[fall_idx]),
        "non_fall_precision": float(precision[0]),
        "non_fall_recall": float(recall[0]),
        "non_fall_f1": float(f1[0]),
        "mean_probs": mean_probs,
        "truth": truth,
    }


def sweep_thresholds(
    truth: np.ndarray, probs: np.ndarray
) -> list[dict[str, float]]:
    records = []
    for t in np.linspace(0.05, 0.95, 19):
        pred = (probs >= t).astype(int)
        precision, recall, f1, _ = precision_recall_fscore_support(
            truth, pred, labels=[0, 1], zero_division=0
        )
        records.append(
            {
                "threshold": float(t),
                "accuracy": float(accuracy_score(truth, pred)),
                "precision": float(precision[1]),
                "recall": float(recall[1]),
                "f1": float(f1[1]),
            }
        )
    return records


# ---------------------------------------------------------------------------
# Main Execution Pipeline
# ---------------------------------------------------------------------------


def run(args: argparse.Namespace) -> int:
    import tensorflow as tf

    setup_logging(args.logs_dir / "export_tflite.log")
    section("STEP 5 - TFLITE INT8 QUANTIZATION & C EXPORT")
    LOGGER.info("TensorFlow version ..... %s", tf.__version__)
    LOGGER.info("Model path ............. %s", args.model_path)
    LOGGER.info("Output dir ............. %s", args.models_dir)

    if not args.model_path.exists():
        LOGGER.error("Model %s does not exist. Run Step 4 first!", args.model_path)
        return 2

    # 1. Load trained Keras composite model
    section("1. LOADING KERAS MODEL & CREATING STATIC BATCH GRAPH")
    keras_model = tf.keras.models.load_model(args.model_path)
    LOGGER.info("Loaded Keras model: %s (%d params)", keras_model.name, keras_model.count_params())

    # Build static-shape model for TFLite Micro: batch=1, (1, 96, 64, 1)
    static_in = tf.keras.Input(
        batch_shape=(1, config.PATCH_FRAMES, config.MEL_BANDS, 1),
        dtype=tf.float32,
        name="log_mel_patch",
    )
    static_out = keras_model(static_in)
    static_model = tf.keras.Model(static_in, static_out, name="yamnet_static_detector")

    # 2. Convert to Float32 TFLite
    section("2. CONVERTING FLOAT32 TFLITE BASELINE")
    f32_converter = tf.lite.TFLiteConverter.from_keras_model(static_model)
    f32_tflite_bytes = f32_converter.convert()
    f32_tflite_path = args.models_dir / "yamnet_fall_detector_float32.tflite"
    with open(f32_tflite_path, "wb") as f:
        f.write(f32_tflite_bytes)
    LOGGER.info("Float32 TFLite saved ... %s (%.2f MB)", f32_tflite_path.name, len(f32_tflite_bytes) / 1e6)

    # 3. Prepare Calibration Data for INT8 PTQ
    section("3. INT8 POST-TRAINING QUANTIZATION (PTQ)")
    chunks_path = args.processed_dir / "chunks_int16.npy"
    train_idx_path = args.splits_dir / "train_indices.npy"
    if not chunks_path.exists() or not train_idx_path.exists():
        LOGGER.error("Missing data artifacts. Run Steps 2 and 3 first!")
        return 2

    chunks = np.load(chunks_path, mmap_mode="r")
    train_indices = np.load(train_idx_path)

    rng = np.random.default_rng(args.seed)
    n_calib = min(args.num_calibration, len(train_indices))
    sample_indices = rng.choice(train_indices, size=n_calib, replace=False)
    LOGGER.info("Sampling %d training windows for calibration...", n_calib)

    # Pre-extract calibration log-mel patches
    calib_waveforms = (chunks[sample_indices].astype(np.float32) / 32768.0)
    calib_patches = ym.build_log_mel(tf.constant(calib_waveforms)).numpy()
    LOGGER.info("Calibration patches shape: %s", calib_patches.shape)

    def representative_dataset_gen():
        for i in range(n_calib):
            yield [calib_patches[i : i + 1].astype(np.float32)]

    # INT8 Quantization configuration
    int8_converter = tf.lite.TFLiteConverter.from_keras_model(static_model)
    int8_converter.optimizations = [tf.lite.Optimize.DEFAULT]
    int8_converter.representative_dataset = representative_dataset_gen
    int8_converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    int8_converter.inference_input_type = tf.int8
    int8_converter.inference_output_type = tf.int8

    LOGGER.info("Running INT8 quantization converter...")
    int8_tflite_bytes = int8_converter.convert()
    int8_tflite_path = args.models_dir / "yamnet_fall_detector_int8.tflite"
    with open(int8_tflite_path, "wb") as f:
        f.write(int8_tflite_bytes)

    ratio = len(f32_tflite_bytes) / len(int8_tflite_bytes)
    LOGGER.info("INT8 TFLite saved ...... %s (%.2f MB)", int8_tflite_path.name, len(int8_tflite_bytes) / 1e6)
    LOGGER.info("Compression ratio ..... %.2fx reduction vs Float32", ratio)

    # 4. Inspect Quantization Parameters & Export C Files
    section("4. QUANTIZATION PARAMETERS & C EXPORT")
    int8_wrapper = TFLiteWrapper(int8_tflite_bytes)
    LOGGER.info("Input Tensor:")
    LOGGER.info("  Shape ............... %s", int8_wrapper.input_details["shape"].tolist())
    LOGGER.info("  Type ................ %s", int8_wrapper.input_details["dtype"].__name__)
    LOGGER.info("  Scale ............... %.8e", int8_wrapper.input_scale)
    LOGGER.info("  Zero point .......... %d", int8_wrapper.input_zero_point)
    LOGGER.info("Output Tensor:")
    LOGGER.info("  Shape ............... %s", int8_wrapper.output_details["shape"].tolist())
    LOGGER.info("  Type ................ %s", int8_wrapper.output_details["dtype"].__name__)
    LOGGER.info("  Scale ............... %.8e", int8_wrapper.output_scale)
    LOGGER.info("  Zero point .......... %d", int8_wrapper.output_zero_point)

    header_path = args.models_dir / "yamnet_model_data.h"
    source_path = args.models_dir / "yamnet_model_data.cc"
    export_c_array(
        int8_tflite_bytes,
        header_path,
        source_path,
        int8_wrapper.input_scale,
        int8_wrapper.input_zero_point,
        int8_wrapper.output_scale,
        int8_wrapper.output_zero_point,
    )
    LOGGER.info("C header exported ..... %s", header_path)
    LOGGER.info("C source exported ..... %s (%.2f MB)", source_path, source_path.stat().st_size / 1e6)

    if args.skip_eval:
        LOGGER.info("\nEvaluation skipped via --skip-eval. Step 5 complete.")
        return 0

    # 5. Parity & Validation on Test & Validation Sets
    section("5. NUMERICAL PARITY & EVALUATION")
    f32_wrapper = TFLiteWrapper(f32_tflite_bytes)

    manifest = pd.read_csv(
        args.splits_dir / "split_manifest.csv",
        dtype={"clip_uid": str, "fold_id": str},
    )
    manifest_by_chunk = manifest.set_index("chunk_index")

    test_indices = np.load(args.splits_dir / "test_indices.npy")
    val_indices = np.load(args.splits_dir / "val_indices.npy")

    eval_splits = {"test": test_indices, "val": val_indices}
    all_results = {
        "model_sizes": {
            "keras_h5_mb": (args.models_dir / "yamnet_fall_detector.h5").stat().st_size / 1e6
            if (args.models_dir / "yamnet_fall_detector.h5").exists()
            else None,
            "float32_tflite_mb": len(f32_tflite_bytes) / 1e6,
            "int8_tflite_mb": len(int8_tflite_bytes) / 1e6,
            "compression_ratio": ratio,
        },
        "quantization": {
            "input_scale": float(int8_wrapper.input_scale),
            "input_zero_point": int(int8_wrapper.input_zero_point),
            "output_scale": float(int8_wrapper.output_scale),
            "output_zero_point": int(int8_wrapper.output_zero_point),
        },
        "splits": {},
    }

    test_pred_cache = {}

    for s_name, indices in eval_splits.items():
        LOGGER.info("\nEvaluating split: %s (%d windows)...", s_name, len(indices))
        split_waveforms = chunks[indices].astype(np.float32) / 32768.0
        split_patches = ym.build_log_mel(tf.constant(split_waveforms)).numpy()

        y_true = manifest_by_chunk.loc[indices, "label_index"].to_numpy()
        uids = manifest_by_chunk.loc[indices, "clip_uid"].to_numpy()

        # Run Keras, Float32 TFLite, INT8 TFLite
        t0 = time.perf_counter()
        p_keras = keras_model.predict(split_patches, batch_size=args.batch_size, verbose=0)
        t_keras = time.perf_counter() - t0

        t0 = time.perf_counter()
        p_f32 = f32_wrapper.predict_batch(split_patches)
        t_f32 = time.perf_counter() - t0

        t0 = time.perf_counter()
        p_int8 = int8_wrapper.predict_batch(split_patches)
        t_int8 = time.perf_counter() - t0

        # Parity analysis
        diff_keras_f32 = np.abs(p_keras - p_f32)[:, 1]
        diff_f32_int8 = np.abs(p_f32 - p_int8)[:, 1]

        LOGGER.info("  Parity: Max diff |Keras - TFLite_F32| = %.2e (mean %.2e)",
                    diff_keras_f32.max(), diff_keras_f32.mean())
        LOGGER.info("  Parity: Max diff |TFLite_F32 - INT8|  = %.2e (mean %.2e)",
                    diff_f32_int8.max(), diff_f32_int8.mean())

        # Window metrics
        w_f32 = compute_metrics(y_true, p_f32)
        w_int8 = compute_metrics(y_true, p_int8)

        # Clip metrics
        c_f32 = compute_clip_metrics(uids, y_true, p_f32)
        c_int8 = compute_clip_metrics(uids, y_true, p_int8)

        if s_name == "test":
            test_pred_cache = {
                "y_true": y_true,
                "uids": uids,
                "p_f32": p_f32,
                "p_int8": p_int8,
                "c_int8": c_int8,
                "diff_f32_int8": diff_f32_int8,
            }

        LOGGER.info("  Window [%s]: F32 Acc=%.4f, INT8 Acc=%.4f (Delta = %+.4f)",
                    s_name, w_f32["accuracy"], w_int8["accuracy"], w_int8["accuracy"] - w_f32["accuracy"])
        LOGGER.info("  Window [%s]: F32 Fall F1=%.4f, INT8 Fall F1=%.4f",
                    s_name, w_f32["fall_f1"], w_int8["fall_f1"])
        LOGGER.info("  Clip   [%s]: F32 Acc=%.4f, INT8 Acc=%.4f (Recall=%.4f, Prec=%.4f)",
                    s_name, c_f32["accuracy"], c_int8["accuracy"], c_int8["fall_recall"], c_int8["fall_precision"])

        all_results["splits"][s_name] = {
            "parity": {
                "max_diff_f32_int8": float(diff_f32_int8.max()),
                "mean_diff_f32_int8": float(diff_f32_int8.mean()),
            },
            "window_f32": w_f32,
            "window_int8": w_int8,
            "clip_f32": {k: v for k, v in c_f32.items() if k not in ("mean_probs", "truth")},
            "clip_int8": {k: v for k, v in c_int8.items() if k not in ("mean_probs", "truth")},
        }

    # 6. Threshold Sweep on Held-out Test Set
    section("6. DECISION THRESHOLD ANALYSIS (TEST SET)")
    clip_truth = test_pred_cache["c_int8"]["truth"]
    clip_probs = test_pred_cache["c_int8"]["mean_probs"]
    sweep_results = sweep_thresholds(clip_truth, clip_probs)
    all_results["threshold_sweep"] = sweep_results

    LOGGER.info("Threshold Sweep on Held-out Test Clips (INT8):")
    LOGGER.info("  Thresh | Accuracy | Precision | Recall |   F1  ")
    LOGGER.info("  -------+----------+-----------+--------+-------")
    for rec in sweep_results:
        LOGGER.info("   %0.2f  |  %0.4f  |   %0.4f  | %0.4f | %0.4f",
                    rec["threshold"], rec["accuracy"], rec["precision"], rec["recall"], rec["f1"])

    # 7. Generate Evaluation Figures
    section("7. GENERATING EVALUATION PLOT")
    fig, axes = plt.subplots(2, 2, figsize=(13, 10))

    # Subplot 1: ROC Curves (Keras Float32 vs INT8)
    fpr_f32, tpr_f32, _ = roc_curve(test_pred_cache["y_true"], test_pred_cache["p_f32"][:, 1])
    fpr_int8, tpr_int8, _ = roc_curve(test_pred_cache["y_true"], test_pred_cache["p_int8"][:, 1])
    axes[0, 0].plot(fpr_f32, tpr_f32, label=f"Float32 TFLite (AUC={all_results['splits']['test']['window_f32']['auc']:.3f})", lw=2)
    axes[0, 0].plot(fpr_int8, tpr_int8, label=f"INT8 TFLite (AUC={all_results['splits']['test']['window_int8']['auc']:.3f})", lw=2, linestyle="--")
    axes[0, 0].plot([0, 1], [0, 1], "k--", alpha=0.5)
    axes[0, 0].set_title("Window-Level ROC Curves (Test Set)")
    axes[0, 0].set_xlabel("False Positive Rate")
    axes[0, 0].set_ylabel("True Positive Rate")
    axes[0, 0].legend(loc="lower right")
    axes[0, 0].grid(True, alpha=0.3)

    # Subplot 2: Probability Differences Histogram (|Float32 - INT8|)
    axes[0, 1].hist(test_pred_cache["diff_f32_int8"], bins=30, color="skyblue", edgecolor="black", alpha=0.8)
    axes[0, 1].axvline(test_pred_cache["diff_f32_int8"].mean(), color="red", linestyle="--",
                       label=f"Mean Error: {test_pred_cache['diff_f32_int8'].mean():.4f}")
    axes[0, 1].set_title("Quantization Error Distribution |P_float32 - P_int8|")
    axes[0, 1].set_xlabel("Absolute Difference in P(fall)")
    axes[0, 1].set_ylabel("Count (Windows)")
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # Subplot 3: Confusion Matrix (INT8 Clip-Level on Test Set)
    cm = np.array(all_results["splits"]["test"]["clip_int8"]["confusion_matrix"])
    im = axes[1, 0].imshow(cm, cmap="Blues", interpolation="nearest")
    axes[1, 0].set_title(f"INT8 Clip-Level Confusion Matrix (Test Set, N={len(clip_truth)})")
    axes[1, 0].set_xticks([0, 1], labels=["Non-Fall", "Fall"])
    axes[1, 0].set_yticks([0, 1], labels=["Non-Fall", "Fall"])
    axes[1, 0].set_xlabel("Predicted Label")
    axes[1, 0].set_ylabel("True Label")
    for i in range(2):
        for j in range(2):
            axes[1, 0].text(j, i, str(cm[i, j]), ha="center", va="center",
                            color="white" if cm[i, j] > cm.max() / 2 else "black", fontsize=14, fontweight="bold")
    plt.colorbar(im, ax=axes[1, 0], fraction=0.046, pad=0.04)

    # Subplot 4: Precision / Recall / F1 vs Decision Threshold
    sw_df = pd.DataFrame(sweep_results)
    axes[1, 1].plot(sw_df["threshold"], sw_df["precision"], marker="o", label="Fall Precision", color="tab:blue")
    axes[1, 1].plot(sw_df["threshold"], sw_df["recall"], marker="s", label="Fall Recall", color="tab:green")
    axes[1, 1].plot(sw_df["threshold"], sw_df["f1"], marker="^", label="Fall F1", color="tab:red", lw=2)
    axes[1, 1].set_title("Clip Performance vs Decision Threshold (Test Set)")
    axes[1, 1].set_xlabel("P(fall) Decision Threshold")
    axes[1, 1].set_ylabel("Score")
    axes[1, 1].set_ylim(-0.05, 1.05)
    axes[1, 1].legend(loc="lower left")
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    fig_path = args.figures_dir / "tflite_eval.png"
    plt.savefig(fig_path, dpi=150)
    plt.close()
    LOGGER.info("Saved evaluation figure ... %s", fig_path)

    # Save metrics JSON
    metrics_path = args.outputs_dir / "tflite_metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2)
    LOGGER.info("Saved metrics JSON ........ %s", metrics_path)

    section("STEP 5 COMPLETE")
    LOGGER.info("Model ready for ESP32-S3-BOX-3 deployment:")
    LOGGER.info("  INT8 FlatBuffer: %s (%.2f MB)", int8_tflite_path, len(int8_tflite_bytes) / 1e6)
    LOGGER.info("  C Header:        %s", header_path)
    LOGGER.info("  C Source:        %s", source_path)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model-path", type=Path, default=config.MODELS_DIR / "yamnet_fall_detector.keras")
    parser.add_argument("--processed-dir", type=Path, default=config.PROCESSED_DIR)
    parser.add_argument("--splits-dir", type=Path, default=config.SPLITS_DIR)
    parser.add_argument("--models-dir", type=Path, default=config.MODELS_DIR)
    parser.add_argument("--outputs-dir", type=Path, default=config.OUTPUTS_DIR)
    parser.add_argument("--figures-dir", type=Path, default=config.FIGURES_DIR)
    parser.add_argument("--logs-dir", type=Path, default=config.LOGS_DIR)
    parser.add_argument("--num-calibration", type=int, default=300, help="Number of calibration samples for INT8 PTQ")
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--seed", type=int, default=config.RANDOM_SEED)
    parser.add_argument("--skip-eval", action="store_true", help="Skip evaluation and only export models")

    args = parser.parse_args()
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
