// Auto-generated by src/5_export_tflite.py
// Acoustic Emergency Alerting System - ESP32-S3-BOX-3 Model Data
#ifndef YAMNET_MODEL_DATA_H_
#define YAMNET_MODEL_DATA_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Model input/output dimensions
#define YAMNET_INPUT_FRAMES       96
#define YAMNET_INPUT_BANDS        64
#define YAMNET_INPUT_CHANNELS     1
#define YAMNET_NUM_CLASSES        2

// Input quantization parameters (int8):
//   quantized_val = round(real_val / YAMNET_INPUT_SCALE) + YAMNET_INPUT_ZERO_POINT
//   real_val      = (quantized_val - YAMNET_INPUT_ZERO_POINT) * YAMNET_INPUT_SCALE
#define YAMNET_INPUT_SCALE        4.22173813e-02f
#define YAMNET_INPUT_ZERO_POINT   28

// Output quantization parameters (int8):
//   probability   = (quantized_val - YAMNET_OUTPUT_ZERO_POINT) * YAMNET_OUTPUT_SCALE
#define YAMNET_OUTPUT_SCALE       3.90625000e-03f
#define YAMNET_OUTPUT_ZERO_POINT  -128

// Model FlatBuffer binary (16-byte aligned for TFLite Micro in PSRAM/Flash)
extern const unsigned char g_yamnet_model_data[];
extern const unsigned int g_yamnet_model_data_len;

#ifdef __cplusplus
}
#endif

#endif  // YAMNET_MODEL_DATA_H_
